/* Generated by Pyrex 0.9.4.1 on Mon Jan  8 09:13:31 2007 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "numpy/arrayobject.h"
#include "proj_api.h"


typedef struct {const char *s; const void **p;} __Pyx_CApiTabEntry; /*proto*/
typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_EndUnpack(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], Py_ssize_t nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static int __Pyx_InitCApi(PyObject *module); /*proto*/
static int __Pyx_ImportModuleCApi(__Pyx_CApiTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from _pyproj_numpy */


struct __pyx_obj_13_pyproj_numpy_Proj {
  PyObject_HEAD
  projPJ projpj;
  PyObject *projparams;
  PyObject *proj_version;
  char (*pjinitstring);
};

static PyTypeObject *__pyx_ptype_13_pyproj_numpy_ndarray = 0;
static PyTypeObject *__pyx_ptype_13_pyproj_numpy_Proj = 0;
static double __pyx_v_13_pyproj_numpy__dg2rad;
static double __pyx_v_13_pyproj_numpy__rad2dg;
static PyObject *__pyx_k4;
static PyObject *__pyx_k5;
static PyObject *__pyx_k6;
static PyObject *__pyx_k7;

/* Implementation of _pyproj_numpy */

static char (__pyx_k3[]) = "1.8.1";

static PyObject *__pyx_n_math;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n___version__;
static PyObject *__pyx_n__transform;
static PyObject *__pyx_n_radians;
static PyObject *__pyx_n_degrees;
static PyObject *__pyx_n_False;

static PyObject *__pyx_k3p;

static PyObject *__pyx_n_iteritems;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_str;
static PyObject *__pyx_n_join;
static PyObject *__pyx_n_RuntimeError;

static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k10p;
static PyObject *__pyx_k11p;

static char (__pyx_k8[]) = "+";
static char (__pyx_k9[]) = "=";
static char (__pyx_k10[]) = " ";
static char (__pyx_k11[]) = "";

static int __pyx_f_13_pyproj_numpy_4Proj___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_13_pyproj_numpy_4Proj___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_projparams = 0;
  PyObject *__pyx_v_pjargs;
  PyObject *__pyx_v_key;
  PyObject *__pyx_v_value;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  static char *__pyx_argnames[] = {"projparams",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_projparams)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_projparams);
  __pyx_v_pjargs = Py_None; Py_INCREF(Py_None);
  __pyx_v_key = Py_None; Py_INCREF(Py_None);
  __pyx_v_value = Py_None; Py_INCREF(Py_None);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":45 */
  Py_INCREF(__pyx_v_projparams);
  Py_DECREF(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projparams);
  ((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projparams = __pyx_v_projparams;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":47 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_v_pjargs);
  __pyx_v_pjargs = __pyx_1;
  __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":48 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_projparams, __pyx_n_iteritems); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_GetIter(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_L2:;
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
      break;
    }
    __pyx_3 = __Pyx_UnpackItem(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = __pyx_3;
    __pyx_3 = 0;
    __pyx_4 = __Pyx_UnpackItem(__pyx_2, 1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_4;
    __pyx_4 = 0;
    if (__Pyx_EndUnpack(__pyx_2, 2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":49 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_pjargs, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    __pyx_3 = PyNumber_Add(__pyx_k8p, __pyx_v_key); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    __pyx_4 = PyNumber_Add(__pyx_3, __pyx_k9p); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_str); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_INCREF(__pyx_v_value);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_value);
    __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_3 = PyNumber_Add(__pyx_4, __pyx_6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_5 = PyNumber_Add(__pyx_3, __pyx_k10p); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_6 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
  }
  __pyx_L3:;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":50 */
  __pyx_3 = PyObject_GetAttr(__pyx_k11p, __pyx_n_join); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_INCREF(__pyx_v_pjargs);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_pjargs);
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  ((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->pjinitstring = PyString_AsString(__pyx_2);
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":52 */
  ((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projpj = pj_init_plus(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->pjinitstring);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":53 */
  __pyx_7 = (pj_errno != 0);
  if (__pyx_7) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":54 */
    __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_RuntimeError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_6 = PyString_FromString(pj_strerrno(pj_errno)); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_6);
    __pyx_6 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":55 */
  __pyx_5 = PyFloat_FromDouble((PJ_VERSION / 100.)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->proj_version);
  ((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->proj_version = __pyx_5;
  __pyx_5 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("_pyproj_numpy.Proj.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_pjargs);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_projparams);
  return __pyx_r;
}

static void __pyx_f_13_pyproj_numpy_4Proj___dealloc__(PyObject *__pyx_v_self); /*proto*/
static char __pyx_doc_13_pyproj_numpy_4Proj___dealloc__[] = "destroy projection definition";
static void __pyx_f_13_pyproj_numpy_4Proj___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":59 */
  pj_free(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projpj);

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_pyproj_numpy.Proj.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_n___class__;

static PyObject *__pyx_f_13_pyproj_numpy_4Proj___reduce__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_13_pyproj_numpy_4Proj___reduce__[] = "special method that allows Proj instance to be pickled";
static PyObject *__pyx_f_13_pyproj_numpy_4Proj___reduce__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":63 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n___class__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projparams);
  PyTuple_SET_ITEM(__pyx_2, 0, ((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projparams);
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_pyproj_numpy.Proj.__reduce__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_size;
static PyObject *__pyx_n_empty;
static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_float64;

static PyObject *__pyx_f_13_pyproj_numpy_4Proj__fwd(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_13_pyproj_numpy_4Proj__fwd[] = "\n forward transformation - lons,lats to x,y (done in place).\n if radians=True, lons/lats are radians instead of degrees.\n if errcheck=True, an exception is raised if the forward transformation is invalid.\n if errcheck=False and the forward transformation is invalid, no exception is\n raised and the platform dependent value HUGE_VAL is returned.\n        ";
static PyObject *__pyx_f_13_pyproj_numpy_4Proj__fwd(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_lons = 0;
  PyArrayObject *__pyx_v_lats = 0;
  PyObject *__pyx_v_radians = 0;
  PyObject *__pyx_v_errcheck = 0;
  projUV __pyx_v_projxyout;
  projUV __pyx_v_projlonlatin;
  int __pyx_v_i;
  Py_ssize_t __pyx_v_npts;
  double __pyx_v_u;
  double __pyx_v_v;
  double (*__pyx_v_lonsdata);
  double (*__pyx_v_latsdata);
  double (*__pyx_v_xdata);
  double (*__pyx_v_ydata);
  PyArrayObject *__pyx_v_x;
  PyArrayObject *__pyx_v_y;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"lons","lats","radians","errcheck",0};
  __pyx_v_radians = __pyx_k4;
  __pyx_v_errcheck = __pyx_k5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO|OO", __pyx_argnames, &__pyx_v_lons, &__pyx_v_lats, &__pyx_v_radians, &__pyx_v_errcheck)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_lons);
  Py_INCREF(__pyx_v_lats);
  Py_INCREF(__pyx_v_radians);
  Py_INCREF(__pyx_v_errcheck);
  __pyx_v_x = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_y = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_lons), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "lons")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_lats), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "lats")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":79 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_lons), __pyx_n_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  __pyx_2 = PyInt_AsSsize_t(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_npts = __pyx_2;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":80 */
  __pyx_v_lonsdata = ((double (*))__pyx_v_lons->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":81 */
  __pyx_v_latsdata = ((double (*))__pyx_v_lats->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":82 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_empty); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_lons), __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_float64); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_1 = 0;
  __pyx_5 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_13_pyproj_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_x));
  __pyx_v_x = ((PyArrayObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":83 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_5, __pyx_n_empty); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = PyObject_GetAttr(((PyObject *)__pyx_v_lats), __pyx_n_shape); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_1, __pyx_n_float64); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_4, __pyx_ptype_13_pyproj_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_y));
  __pyx_v_y = ((PyArrayObject *)__pyx_4);
  __pyx_4 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":84 */
  __pyx_v_xdata = ((double (*))__pyx_v_x->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":85 */
  __pyx_v_ydata = ((double (*))__pyx_v_y->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":86 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_npts; ++__pyx_v_i) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":87 */
    __pyx_6 = PyObject_IsTrue(__pyx_v_radians); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    if (__pyx_6) {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":88 */
      __pyx_v_projlonlatin.u = (__pyx_v_lonsdata[__pyx_v_i]);

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":89 */
      __pyx_v_projlonlatin.v = (__pyx_v_latsdata[__pyx_v_i]);
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":91 */
      __pyx_v_projlonlatin.u = (__pyx_v_13_pyproj_numpy__dg2rad * (__pyx_v_lonsdata[__pyx_v_i]));

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":92 */
      __pyx_v_projlonlatin.v = (__pyx_v_13_pyproj_numpy__dg2rad * (__pyx_v_latsdata[__pyx_v_i]));
    }
    __pyx_L4:;

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":93 */
    __pyx_v_projxyout = pj_fwd(__pyx_v_projlonlatin,((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projpj);

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":94 */
    __pyx_5 = __pyx_v_errcheck;
    Py_INCREF(__pyx_5);
    __pyx_6 = PyObject_IsTrue(__pyx_5); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    if (__pyx_6) {
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyInt_FromLong((pj_errno != 0)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    }
    __pyx_6 = PyObject_IsTrue(__pyx_5); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    if (__pyx_6) {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":95 */
      __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_RuntimeError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      __pyx_1 = PyString_FromString(pj_strerrno(pj_errno)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
      __pyx_1 = 0;
      __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __Pyx_Raise(__pyx_5, 0, 0);
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
      goto __pyx_L5;
    }
    __pyx_L5:;

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":96 */
    (__pyx_v_xdata[__pyx_v_i]) = __pyx_v_projxyout.u;

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":97 */
    (__pyx_v_ydata[__pyx_v_i]) = __pyx_v_projxyout.v;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":98 */
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_x));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject *)__pyx_v_x));
  Py_INCREF(((PyObject *)__pyx_v_y));
  PyTuple_SET_ITEM(__pyx_1, 1, ((PyObject *)__pyx_v_y));
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pyproj_numpy.Proj._fwd");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_lons);
  Py_DECREF(__pyx_v_lats);
  Py_DECREF(__pyx_v_radians);
  Py_DECREF(__pyx_v_errcheck);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pyproj_numpy_4Proj__inv(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_13_pyproj_numpy_4Proj__inv[] = "\n inverse transformation - x,y to lons,lats (done in place).\n if radians=True, lons/lats are radians instead of degrees.\n if errcheck=True, an exception is raised if the inverse transformation is invalid.\n if errcheck=False and the inverse transformation is invalid, no exception is\n raised and the platform dependent value HUGE_VAL is returned.\n        ";
static PyObject *__pyx_f_13_pyproj_numpy_4Proj__inv(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_x = 0;
  PyArrayObject *__pyx_v_y = 0;
  PyObject *__pyx_v_radians = 0;
  PyObject *__pyx_v_errcheck = 0;
  projUV __pyx_v_projxyin;
  projUV __pyx_v_projlonlatout;
  int __pyx_v_i;
  Py_ssize_t __pyx_v_npts;
  double __pyx_v_u;
  double __pyx_v_v;
  double (*__pyx_v_xdata);
  double (*__pyx_v_ydata);
  double (*__pyx_v_lonsdata);
  double (*__pyx_v_latsdata);
  PyArrayObject *__pyx_v_lons;
  PyArrayObject *__pyx_v_lats;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"x","y","radians","errcheck",0};
  __pyx_v_radians = __pyx_k6;
  __pyx_v_errcheck = __pyx_k7;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO|OO", __pyx_argnames, &__pyx_v_x, &__pyx_v_y, &__pyx_v_radians, &__pyx_v_errcheck)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  Py_INCREF(__pyx_v_y);
  Py_INCREF(__pyx_v_radians);
  Py_INCREF(__pyx_v_errcheck);
  __pyx_v_lons = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_lats = ((PyArrayObject *)Py_None); Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_x), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "x")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_y), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "y")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":114 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_x), __pyx_n_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_2 = PyInt_AsSsize_t(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_npts = __pyx_2;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":115 */
  __pyx_v_xdata = ((double (*))__pyx_v_x->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":116 */
  __pyx_v_ydata = ((double (*))__pyx_v_y->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":117 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_empty); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_x), __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_float64); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
  __pyx_1 = 0;
  __pyx_5 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_13_pyproj_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_lons));
  __pyx_v_lons = ((PyArrayObject *)__pyx_1);
  __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":118 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_5, __pyx_n_empty); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = PyObject_GetAttr(((PyObject *)__pyx_v_y), __pyx_n_shape); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_1, __pyx_n_float64); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__Pyx_TypeTest(__pyx_4, __pyx_ptype_13_pyproj_numpy_ndarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_lats));
  __pyx_v_lats = ((PyArrayObject *)__pyx_4);
  __pyx_4 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":119 */
  __pyx_v_lonsdata = ((double (*))__pyx_v_lons->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":120 */
  __pyx_v_latsdata = ((double (*))__pyx_v_lats->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":121 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_npts; ++__pyx_v_i) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":122 */
    __pyx_v_projxyin.u = (__pyx_v_xdata[__pyx_v_i]);

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":123 */
    __pyx_v_projxyin.v = (__pyx_v_ydata[__pyx_v_i]);

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":124 */
    __pyx_v_projlonlatout = pj_inv(__pyx_v_projxyin,((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projpj);

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":125 */
    __pyx_5 = __pyx_v_errcheck;
    Py_INCREF(__pyx_5);
    __pyx_6 = PyObject_IsTrue(__pyx_5); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    if (__pyx_6) {
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyInt_FromLong((pj_errno != 0)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    }
    __pyx_6 = PyObject_IsTrue(__pyx_5); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    if (__pyx_6) {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":126 */
      __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_RuntimeError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      __pyx_1 = PyString_FromString(pj_strerrno(pj_errno)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
      __pyx_1 = 0;
      __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __Pyx_Raise(__pyx_5, 0, 0);
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":127 */
    __pyx_6 = PyObject_IsTrue(__pyx_v_radians); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
    if (__pyx_6) {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":128 */
      (__pyx_v_lonsdata[__pyx_v_i]) = __pyx_v_projlonlatout.u;

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":129 */
      (__pyx_v_latsdata[__pyx_v_i]) = __pyx_v_projlonlatout.v;
      goto __pyx_L5;
    }
    /*else*/ {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":131 */
      (__pyx_v_lonsdata[__pyx_v_i]) = (__pyx_v_13_pyproj_numpy__rad2dg * __pyx_v_projlonlatout.u);

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":132 */
      (__pyx_v_latsdata[__pyx_v_i]) = (__pyx_v_13_pyproj_numpy__rad2dg * __pyx_v_projlonlatout.v);
    }
    __pyx_L5:;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":133 */
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_INCREF(((PyObject *)__pyx_v_lons));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject *)__pyx_v_lons));
  Py_INCREF(((PyObject *)__pyx_v_lats));
  PyTuple_SET_ITEM(__pyx_1, 1, ((PyObject *)__pyx_v_lats));
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pyproj_numpy.Proj._inv");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_lons);
  Py_DECREF(__pyx_v_lats);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  Py_DECREF(__pyx_v_radians);
  Py_DECREF(__pyx_v_errcheck);
  return __pyx_r;
}

static PyObject *__pyx_n_True;

static PyObject *__pyx_f_13_pyproj_numpy_4Proj_is_latlong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pyproj_numpy_4Proj_is_latlong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":138 */
  __pyx_v_i = pj_is_latlong(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projpj);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":139 */
  __pyx_1 = __pyx_v_i;
  if (__pyx_1) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":140 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_True); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":142 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pyproj_numpy.Proj.is_latlong");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_13_pyproj_numpy_4Proj_is_geocent(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pyproj_numpy_4Proj_is_geocent(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":147 */
  __pyx_v_i = pj_is_geocent(((struct __pyx_obj_13_pyproj_numpy_Proj *)__pyx_v_self)->projpj);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":148 */
  __pyx_1 = __pyx_v_i;
  if (__pyx_1) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":149 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_True); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":151 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_pyproj_numpy.Proj.is_geocent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_dtype;
static PyObject *__pyx_n_bool;
static PyObject *__pyx_n_is_latlong;


static PyObject *__pyx_f_13_pyproj_numpy__transform(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_13_pyproj_numpy__transform(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_13_pyproj_numpy_Proj *__pyx_v_p1 = 0;
  struct __pyx_obj_13_pyproj_numpy_Proj *__pyx_v_p2 = 0;
  PyArrayObject *__pyx_v_inx = 0;
  PyArrayObject *__pyx_v_iny = 0;
  PyArrayObject *__pyx_v_inz = 0;
  PyObject *__pyx_v_radians = 0;
  double (*__pyx_v_xx);
  double (*__pyx_v_yy);
  double (*__pyx_v_zz);
  int __pyx_v_i;
  Py_ssize_t __pyx_v_npts;
  PyObject *__pyx_v_ierr;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"p1","p2","inx","iny","inz","radians",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOOO", __pyx_argnames, &__pyx_v_p1, &__pyx_v_p2, &__pyx_v_inx, &__pyx_v_iny, &__pyx_v_inz, &__pyx_v_radians)) return 0;
  Py_INCREF(__pyx_v_p1);
  Py_INCREF(__pyx_v_p2);
  Py_INCREF(__pyx_v_inx);
  Py_INCREF(__pyx_v_iny);
  Py_INCREF(__pyx_v_inz);
  Py_INCREF(__pyx_v_radians);
  __pyx_v_ierr = Py_None; Py_INCREF(Py_None);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_p1), __pyx_ptype_13_pyproj_numpy_Proj, 1, "p1")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_p2), __pyx_ptype_13_pyproj_numpy_Proj, 1, "p2")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_inx), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "inx")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_iny), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "iny")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_inz), __pyx_ptype_13_pyproj_numpy_ndarray, 1, "inz")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":158 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_inx), __pyx_n_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_2 = PyInt_AsSsize_t(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_npts = __pyx_2;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":159 */
  __pyx_v_xx = ((double (*))__pyx_v_inx->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":160 */
  __pyx_v_yy = ((double (*))__pyx_v_iny->data);

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":161 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_inz), __pyx_n_dtype); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_dtype); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  Py_INCREF(__pyx_n_bool);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_n_bool);
  __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_Cmp(__pyx_1, __pyx_5, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_6 = __pyx_6 != 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_6) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":162 */
    __pyx_v_zz = ((double (*))__pyx_v_inz->data);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":163 */
  __pyx_6 = PyObject_IsTrue(__pyx_v_radians); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong((!__pyx_6)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  __pyx_6 = PyObject_IsTrue(__pyx_4); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  if (__pyx_6) {
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_p1), __pyx_n_is_latlong); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
    __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
  }
  __pyx_6 = PyObject_IsTrue(__pyx_4); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_6) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":164 */
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_npts; ++__pyx_v_i) {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":165 */
      (__pyx_v_xx[__pyx_v_i]) = ((__pyx_v_xx[__pyx_v_i]) * __pyx_v_13_pyproj_numpy__dg2rad);

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":166 */
      (__pyx_v_yy[__pyx_v_i]) = ((__pyx_v_yy[__pyx_v_i]) * __pyx_v_13_pyproj_numpy__dg2rad);
      __pyx_L4:;
    }
    __pyx_L5:;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":167 */
  __pyx_5 = PyObject_GetAttr(((PyObject *)__pyx_v_inz), __pyx_n_dtype); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_numpy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_1 = PyObject_GetAttr(__pyx_3, __pyx_n_dtype); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  Py_INCREF(__pyx_n_bool);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_n_bool);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_Cmp(__pyx_5, __pyx_3, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_6 = __pyx_6 != 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_6) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":168 */
    __pyx_1 = PyInt_FromLong(pj_transform(__pyx_v_p1->projpj,__pyx_v_p2->projpj,__pyx_v_npts,0,__pyx_v_xx,__pyx_v_yy,__pyx_v_zz)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ierr);
    __pyx_v_ierr = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":170 */
    __pyx_4 = PyInt_FromLong(pj_transform(__pyx_v_p1->projpj,__pyx_v_p2->projpj,__pyx_v_npts,0,__pyx_v_xx,__pyx_v_yy,0)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ierr);
    __pyx_v_ierr = __pyx_4;
    __pyx_4 = 0;
  }
  __pyx_L6:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":171 */
  __pyx_5 = PyInt_FromLong(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_v_ierr, __pyx_5, &__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  __pyx_6 = __pyx_6 != 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_6) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":172 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_RuntimeError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    __pyx_6 = PyInt_AsLong(__pyx_v_ierr); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    __pyx_1 = PyString_FromString(pj_strerrno(__pyx_6)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_5, 0, 0);
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":173 */
  __pyx_6 = PyObject_IsTrue(__pyx_v_radians); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong((!__pyx_6)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_6 = PyObject_IsTrue(__pyx_1); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  if (__pyx_6) {
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_3 = PyObject_GetAttr(((PyObject *)__pyx_v_p2), __pyx_n_is_latlong); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
    __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }
  __pyx_6 = PyObject_IsTrue(__pyx_1); if (__pyx_6 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_6) {

    /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":174 */
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_npts; ++__pyx_v_i) {

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":175 */
      (__pyx_v_xx[__pyx_v_i]) = ((__pyx_v_xx[__pyx_v_i]) * __pyx_v_13_pyproj_numpy__rad2dg);

      /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":176 */
      (__pyx_v_yy[__pyx_v_i]) = ((__pyx_v_yy[__pyx_v_i]) * __pyx_v_13_pyproj_numpy__rad2dg);
      __pyx_L9:;
    }
    __pyx_L10:;
    goto __pyx_L8;
  }
  __pyx_L8:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pyproj_numpy._transform");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ierr);
  Py_DECREF(__pyx_v_p1);
  Py_DECREF(__pyx_v_p2);
  Py_DECREF(__pyx_v_inx);
  Py_DECREF(__pyx_v_iny);
  Py_DECREF(__pyx_v_inz);
  Py_DECREF(__pyx_v_radians);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_False, "False"},
  {&__pyx_n_RuntimeError, "RuntimeError"},
  {&__pyx_n_True, "True"},
  {&__pyx_n___class__, "__class__"},
  {&__pyx_n___version__, "__version__"},
  {&__pyx_n__transform, "_transform"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_bool, "bool"},
  {&__pyx_n_degrees, "degrees"},
  {&__pyx_n_dtype, "dtype"},
  {&__pyx_n_empty, "empty"},
  {&__pyx_n_float64, "float64"},
  {&__pyx_n_is_latlong, "is_latlong"},
  {&__pyx_n_iteritems, "iteritems"},
  {&__pyx_n_join, "join"},
  {&__pyx_n_math, "math"},
  {&__pyx_n_numpy, "numpy"},
  {&__pyx_n_radians, "radians"},
  {&__pyx_n_shape, "shape"},
  {&__pyx_n_size, "size"},
  {&__pyx_n_str, "str"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_13_pyproj_numpy_Proj(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_13_pyproj_numpy_Proj *p = (struct __pyx_obj_13_pyproj_numpy_Proj *)o;
  p->projparams = Py_None; Py_INCREF(Py_None);
  p->proj_version = Py_None; Py_INCREF(Py_None);
  if (__pyx_f_13_pyproj_numpy_4Proj___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_13_pyproj_numpy_Proj(PyObject *o) {
  struct __pyx_obj_13_pyproj_numpy_Proj *p = (struct __pyx_obj_13_pyproj_numpy_Proj *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_13_pyproj_numpy_4Proj___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->projparams);
  Py_XDECREF(p->proj_version);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_13_pyproj_numpy_Proj(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_13_pyproj_numpy_Proj *p = (struct __pyx_obj_13_pyproj_numpy_Proj *)o;
  if (p->projparams) {
    e = (*v)(p->projparams, a); if (e) return e;
  }
  if (p->proj_version) {
    e = (*v)(p->proj_version, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_13_pyproj_numpy_Proj(PyObject *o) {
  struct __pyx_obj_13_pyproj_numpy_Proj *p = (struct __pyx_obj_13_pyproj_numpy_Proj *)o;
  Py_XDECREF(p->projparams);
  p->projparams = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->proj_version);
  p->proj_version = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_13_pyproj_numpy_Proj[] = {
  {"__reduce__", (PyCFunction)__pyx_f_13_pyproj_numpy_4Proj___reduce__, METH_VARARGS|METH_KEYWORDS, __pyx_doc_13_pyproj_numpy_4Proj___reduce__},
  {"_fwd", (PyCFunction)__pyx_f_13_pyproj_numpy_4Proj__fwd, METH_VARARGS|METH_KEYWORDS, __pyx_doc_13_pyproj_numpy_4Proj__fwd},
  {"_inv", (PyCFunction)__pyx_f_13_pyproj_numpy_4Proj__inv, METH_VARARGS|METH_KEYWORDS, __pyx_doc_13_pyproj_numpy_4Proj__inv},
  {"is_latlong", (PyCFunction)__pyx_f_13_pyproj_numpy_4Proj_is_latlong, METH_VARARGS|METH_KEYWORDS, 0},
  {"is_geocent", (PyCFunction)__pyx_f_13_pyproj_numpy_4Proj_is_geocent, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_13_pyproj_numpy_Proj[] = {
  {"projparams", T_OBJECT, offsetof(struct __pyx_obj_13_pyproj_numpy_Proj, projparams), 0, 0},
  {"proj_version", T_OBJECT, offsetof(struct __pyx_obj_13_pyproj_numpy_Proj, proj_version), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Proj = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Proj = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Proj = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Proj = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_13_pyproj_numpy_Proj = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_pyproj_numpy.Proj", /*tp_name*/
  sizeof(struct __pyx_obj_13_pyproj_numpy_Proj), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_13_pyproj_numpy_Proj, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Proj, /*tp_as_number*/
  &__pyx_tp_as_sequence_Proj, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Proj, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Proj, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_13_pyproj_numpy_Proj, /*tp_traverse*/
  __pyx_tp_clear_13_pyproj_numpy_Proj, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_13_pyproj_numpy_Proj, /*tp_methods*/
  __pyx_members_13_pyproj_numpy_Proj, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_13_pyproj_numpy_Proj, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"_transform", (PyCFunction)__pyx_f_13_pyproj_numpy__transform, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_pyproj_numpy(void); /*proto*/
PyMODINIT_FUNC init_pyproj_numpy(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  double __pyx_4;
  PyObject *__pyx_5 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_pyproj_numpy", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;};
  __pyx_ptype_13_pyproj_numpy_ndarray = __Pyx_ImportType("numpy", "ndarray", sizeof(PyArrayObject)); if (!__pyx_ptype_13_pyproj_numpy_ndarray) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_type_13_pyproj_numpy_Proj.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_13_pyproj_numpy_Proj) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Proj", (PyObject *)&__pyx_type_13_pyproj_numpy_Proj) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  __pyx_ptype_13_pyproj_numpy_Proj = &__pyx_type_13_pyproj_numpy_Proj;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":3 */
  __pyx_1 = __Pyx_Import(__pyx_n_math, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_math, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":4 */
  __pyx_1 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numpy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 4; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":5 */
  import_array();

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":8 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_math); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_radians); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyFloat_FromDouble(1.); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_13_pyproj_numpy__dg2rad = __pyx_4;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":9 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_math); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_degrees); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyFloat_FromDouble(1.); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyFloat_AsDouble(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_13_pyproj_numpy__rad2dg = __pyx_4;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":10 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___version__, __pyx_k3p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":65 */
  __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  __pyx_k4 = __pyx_3;
  __pyx_3 = 0;
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  __pyx_k5 = __pyx_2;
  __pyx_2 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":100 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_k6 = __pyx_1;
  __pyx_1 = 0;
  __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_k7 = __pyx_5;
  __pyx_5 = 0;

  /* "/Volumes/User/jsw/python/pyproj/_pyproj_numpy.pyx":153 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_pyproj_numpy");
}

static char *__pyx_filenames[] = {
  "_pyproj_numpy.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_UnpackError(void) {
    PyErr_SetString(PyExc_ValueError, "unpack sequence of wrong size");
}

static PyObject *__Pyx_UnpackItem(PyObject *seq, Py_ssize_t i) {
  PyObject *item;
  if (!(item = PySequence_GetItem(seq, i))) {
    if (PyErr_ExceptionMatches(PyExc_IndexError))
    	__Pyx_UnpackError();
  }
  return item;
}

static int __Pyx_EndUnpack(PyObject *seq, Py_ssize_t i) {
  PyObject *item;
  if (item = PySequence_GetItem(seq, i)) {
    Py_DECREF(item);
    __Pyx_UnpackError();
    return -1;
  }
  PyErr_Clear();
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_CheckExact(type)) {
        /* Raising builtin string is deprecated but still allowed --
         * do nothing.  Raising an instance of a new-style str
         * subclass is right out. */
        if (PyErr_Warn(PyExc_DeprecationWarning,
                   "raising a string exception is deprecated"))
                goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /* PyErr_NormalizeException(&type, &value, &tb); */
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else if (PyType_IsSubtype(type->ob_type, (PyTypeObject*)PyExc_Exception)) {
        /* Raising a new-style object (in Py2.5).
           The value should be a dummy. */
        if (value != Py_None) {
                PyErr_SetString(PyExc_TypeError,
                  "instance exception may not have a separate value");
                goto raise_error;
        }
        else {
                /* Normalize to raise <class>, <instance> */
                Py_DECREF(value);
                value = type;
                type = (PyObject*) type->ob_type;
                Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                     "exceptions must be classes, instances, or "
                     "strings (deprecated), not %s",
                     type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
