from typing import Optional

def _pyproj_global_context_initialize() -> None: ...
def get_user_data_dir(create: bool = False) -> str: ...
def _global_context_set_data_dir() -> None: ...
def set_use_global_context(active: Optional[bool] = None) -> None: ...
def set_global_context_network(active: Optional[bool] = None) -> None: ...
def is_global_context_network_enabled() -> bool: ...
