from pathlib import Path
from typing import Optional, Union

def _pyproj_global_context_initialize() -> None: ...
def get_user_data_dir(create: bool = False) -> str: ...
def set_ca_bundle_path(ca_bundle_path: Union[Path, str, bool, None] = None) -> None: ...
def _global_context_set_data_dir() -> None: ...
def set_use_global_context(active: Optional[bool] = None) -> None: ...
def set_global_context_network(active: Optional[bool] = None) -> None: ...
def is_global_context_network_enabled() -> bool: ...
